title: Marine Plastic Explorer
baseurl: ''
imageurl: 'https://unfolddata.github.io/marine-plastic-explorer/assets/uploads'
siteurl: 'https://unfolddata.github.io/marine-plastic-explorer/'
permalink: /:categories/:title
markdown: kramdown
languages: &languages
  - name: 'English'
    value: 'en'
exclude:
  - app
  - internals
  - server
prose:
  media: "assets/uploads"
  rooturl: '_posts'
  siteurl: 'https://unfolddata.github.io/marine-plastic-explorer/'
  _posts:
    - name: "layout"
      field:
        element: "hidden"
        value: "default"
    - name: "permalink"
      field:
        element: "text"
        label: "Permalink"
        value: "/"
    - name: "title"
      field:
        element: "text"
        label: "Title"
        value: ""
